ERPLOWCOST/urls.py
from django.contrib import admin
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('' , include('api.v1.module.urls'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/v1/module/matrial/urls.py
from django.http import JsonResponse
from django.urls import path, re_path, include
from api.v1.module.matrial.matrial_controller import *
from api.v1.module.matrial.home_controller import *
from api.v1.module.matrial.labour_controller import *
from api.v1.module.matrial.contact_controller import *

urlpatterns = [
  path('', IndexView.as_view(), name='home'),
  path('matrial-list/', MatrialListView.as_view(), name='matrial-list'),
  path('matrial-add/', MatrialView.as_view(), name='matrial-add'),
  path('matrial-update/<int:pk>/', MatrialUpdateView.as_view(), name='matrial-update'),
  path('matrial-delete/', MatrialDeleteView.as_view(), name='matrial-delete'),
  path('about/', AboutView.as_view(), name='about'),
  path('contact/', ConatctView.as_view(), name='contact'),
  path('labour-list/', LabourListView.as_view(), name='labour-list'),
  path('labour-add/', LabourView.as_view(), name='labour-add'),
  path('labour-update/<int:pk>/', LabourUpdateView.as_view(), name='labour-update'),
  path('labour-delete/', LabourDeleteView.as_view(), name='labour-delete'),
  path('contact-list/', ContactListView.as_view(), name='contact-list'),
  path('contact-add/', ContactView.as_view(), name='contact-add'),
  path('contact-update/', ContactUpdateView.as_view(), name='contact-update'),
  path('contact-delete/', ContactDeleteView.as_view(), name='contact-delete'),
  path('matrial-fav/<int:matrial_id>/', FavoriteMatrialAdd.as_view(), name='matrial-fav'),
  path('labour-fav/<int:labour_id>/', FavoriteLabourAdd.as_view(), name='labour-fav'),
  path('matrial-com/<int:matrial_id>/', CompressionMatrialAdd.as_view(), name='matrial-com'),
  path('labour-com/<int:labour_id>/', CompressionLabourAdd.as_view(), name='labour-com'),
  path('fav-list/', FavList.as_view(), name='fav-list'),
  path('com-list/', ComList.as_view(), name='com-list'),
  path('labour-filter/', FilterLabour.as_view(), name='labour-filter/'),
  path('labour-review-add/<int:pk>/', LabourReviewView.as_view(), name='labour-review-add'),
  path('matrial-review-add/<int:pk>/', MatrialReviewView.as_view(), name='matrial-review-add'),

]

                                                                                                                                                                                         


                                                                                                                                                                                         

api/v1/module/urls.py
from django.urls import path,include 

urlpatterns = [
  path('',include('api.v1.module.matrial.urls')),
]

contact/models.py
from django.db import models

# Create your models here.
class Contact(models.Model):
    name = models.CharField(max_length=250)
    mobile = models.CharField(max_length=10)
    desc = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

labour/models.py
from django.db import models

# Create your models here.
class Labour(models.Model):
    name = models.CharField(max_length=250)
    mobile = models.CharField(max_length=10)
    expert_title = models.CharField(max_length=250)
    desc = models.TextField()
    updated_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now=True)
    address = models.CharField(max_length=999 , null = True , blank=  True)
    image = models.FileField(upload_to="labour_image/", null = True , blank=  True)


class LabourReview(models.Model):
    labour = models.ForeignKey(Labour , on_delete=models.CASCADE , related_name="labour_review")
    user_name = models.CharField(max_length=250)
    mobile = models.CharField(max_length=10)
    desc = models.TextField()
    updated_at = models.DateTimeField(auto_now_add=True)
    created_at = models.DateTimeField(auto_now=True)

material/models.py
from django.db import models

# Create your models here.

class Matrial(models.Model):
    type = models.CharField(max_length=250)
    name = models.CharField(max_length=999)
    brand = models.CharField(max_length=250)
    start_rate = models.FloatField()
    end_rate  = models.FloatField()
    desc = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    image = models.FileField(upload_to="matrial_image" , null= True , blank=True)


class MatrialReview(models.Model):
    matrial = models.ForeignKey(Matrial , on_delete=models.CASCADE , related_name="matrial_review")
    user_name = models.CharField(max_length=250)
    contact_number = models.CharField(max_length=10)
    desc = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

api/v1/module/forms/contact_forms.py
from django import forms
from contact.models import Contact

# Creating a ModelForm
class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = "__all__"

api/v1/module/forms/labour_forms.py
from django import forms
from labour.models import Labour , LabourReview

# Creating a ModelForm
class LabourForm(forms.ModelForm):
    class Meta:
        model = Labour
        fields = "__all__"

# Creating a ModelForm
class LabourReviewForm(forms.ModelForm):
    class Meta:
        model = LabourReview
        fields = "__all__"

api/v1/module/forms/matrial_forms.py
from django import forms
from material.models import *
# creating a form
class MatrialForm(forms.ModelForm):
    class Meta:
        model = Matrial
        fields = "__all__"
        
class MatrialReviewForm(forms.ModelForm):
    class Meta:
        model = MatrialReview
        fields = "__all__"

contact/views.py
from django.shortcuts import render

# Create your views here.

labour/views.py
from django.shortcuts import render

# Create your views here.

material/views.py
from django.shortcuts import render

# Create your views here.

templates/favorite.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}Favorite List{% endblock %}</title>
{% block body %}
		<section class="product-sec space favorite-sec">
			<div class="container">
				<h3 class="subhead d-flex justify-content-between text-white">Labour For Sale In Jaipur
				<a href="javascript:void(0);" class="primary-clr fz-16 fw-400">Remove All</a>
				</h3>
				<div class="row">
					{% for x in labour_list %}
					<div class="col-lg-3 col-md-6 col-sm-6">
						<div class="product-innr">
							<div class="product-img">
								<img src="{{x.image.url}}" alt="">
								<span class="product-rating"><i class="fas fa-star"></i> 4.9</span>
							</div>
							<div class="product-content">
								<h4><a href="/labour-update/{{x.pk}}/">{{x.expert_title}}</a></h4>
								<p><i class="fas fa-map-marker-alt me-1"></i> {{x.address}}</p>
								<h6 class="text-white">{{x.name}}</h6>
								
								<div class="product-prc">
									<div>
										<p>{{x.mobile}}</p>
									</div>
									<div>
										<a href="javascript:void(0);" class="labour-fav-delete" data-id="{{ x.id }}"><i class="far fa-bookmark"></i></a>
										<a href="javascript:void(0);" class="labour-com-delete" data-id="{{ x.id }}"><i class="fas fa-sliders-h"></i></a>
									</div>
								</div>
							</div>
							<div class="product-social">
								<a href="javascript:void(0);"><i class="far fa-phone fa-rotate-90"></i></a>
								<a href="javascript:void(0);"><i class="fab fa-whatsapp"></i></a>
								<a href="javascript:void(0);"><i class="far fa-envelope"></i></a>
							</div>
						</div>
					</div>
					{% endfor %}
				</div>
			</div>
			<div class="container mt-5">
				<h3 class="subhead d-flex justify-content-between text-white">Matrial For Sale In Jaipur
				<a href="javascript:void(0);" class="primary-clr fz-16 fw-400">Remove All</a>
				</h3>
				<div class="row">
					{% for x in material_list %}
					<div class="col-lg-3 col-md-6 col-sm-6">
						<div class="product-innr">
						<div class="product-img">
							<img src="{{x.image.url}}" alt="">
							<span class="product-rating"><i class="fas fa-star"></i> 4.9</span>
						</div>
						<div class="product-content">
							<h4><a href="/matrial-update/{{x.pk}}/">{{x.name}}</a></h4>
							<!-- <p><i class="fas fa-map-marker-alt me-1"></i> {{x.name}}</p> -->
							<h6 class="text-white">{{x.type}}</h6>
							
							<div class="product-prc">
								<div>
									<p>INR {{x.start_rate}}-{{x.end_rate}}</p>
								</div>
								<div>
									<a href="javascript:void(0);" class="matrial-fav-delete" data-id="{{ x.id }}"><i class="far fa-bookmark"></i></a>
									<a href="javascript:void(0);" class="matrial-com-delete" data-id="{{ x.id }}"><i class="fas fa-sliders-h"></i></a>
								</div>
							</div>
						</div>
						<div class="product-social">
							<a href="javascript:void(0);"><i class="far fa-phone fa-rotate-90"></i></a>
							<a href="javascript:void(0);"><i class="fab fa-whatsapp"></i></a>
							<a href="javascript:void(0);"><i class="far fa-envelope"></i></a>
						</div>
					</div>
					</div>
					{% endfor %}
				</div>
			</div>
		</section>
		<section class="cta-sec tp-space">
			<div class="container">
				<div class="heading new-head">
					<div class="heading-icon">
						<img src="{% static 'assets/images/heading-icon.png' %}" alt="">
					</div>
					<div class="heading-content">
						<h3>Advisory Experts</h3>
						<p>Fill form below and our agent will contact you shortly</p>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<div class="cta-innr">
							<form action="" id="contact-add" class="row align-items-end">
								{% csrf_token %}
								<div class="col-lg-3 col-md-6 col-sm-6 mb-5">
									<input type="text" name="name" class="form-control" placeholder="Enter Name">
								</div>
								<div class="col-lg-3 col-md-6 col-sm-6 mb-5">
									<input type="number" name="mobile" class="form-control" placeholder="Enter Phone Number">
								</div>
								<div class="col-lg-3 col-md-6 col-sm-6 mb-5">
									<textarea name="desc" id="" class="form-control" placeholder="Enter Description"></textarea>
									
								</div>
								<div class="col-lg-3 col-md-6 col-sm-6 mb-5">
									<button class="thm-btn w-75" type="submit">Send</button>
								</div>
							</form>
							<div class="row justify-content-center">
								<div class="col-lg-4">
									<div class="product-social">
										<a href="javascript:void(0);"><i class="far fa-phone fa-rotate-90"></i></a>
										<a href="javascript:void(0);"><i class="fab fa-whatsapp"></i></a>
										<a href="javascript:void(0);"><i class="far fa-envelope"></i></a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		{% endblock body %}

templates/index.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}Home{% endblock %}</title>
{% block body %}
	
<section class="bannr-sec">
	<div class="container">
		<div class="row justify-content-center">
			<div class="col-lg-6">
				<div class="bannr-content text-center">
					<h1 class="text-white">LowCost Construction</h1>
					<p>Providing Low-Cost Construction Services for Your Dream Projects</p>
				</div>
			</div>
		</div>
	</div>
</section>

<section class="about-sec tp-space">
	<div class="container">
		<div class="heading">
			<div class="heading-icon">
				<img src="{% static 'assets/images/heading-icon.png' %}" alt="">
			</div>
			<div class="heading-content">
				<h3>About Us</h3>
				<h6 class="text-white">Building Affordable Homes with Quality Construction</h6>
			</div>
		</div>
		<div class="row">
			<div class="col-xl-7 col-lg-12 col-md-12 col-sm-12">
				<div class="row">
					<div class="col-lg-6 col-md-6 col-sm-6">
						<div class="about-lft-img">
							<img src="{% static 'assets/images/about1.webp' %}" alt="">
						</div>
					</div>
					<div class="col-lg-6 col-md-6 col-sm-6">
						<p class="mb-5">LowCost Construction started in 2025 with a mission to provide affordable and high-quality construction services. We specialize in supplying construction materials and labor for all your construction needs. Our licensed team, including experts, ensures the highest standards for every project, from materials supply to labor management.</p>
						<a href="tel:9887701938" class="thm-btn">Enquiry Now</a>
					</div>
					<div class="col-lg-12 about-count">
						<ul class="row g-2 justify-content-center">
							<li class="col-lg-3 col-md-3 col-sm-4 col-6">
								<div class="about-count-innr">
									<h4 class="text-white"><span class="counter">{{labour_count}}</span> +</h4>
									<p>SKILLED WORKERS</p>
								</div>
							</li>
							<li class="col-lg-3 col-md-3 col-sm-4 col-6">
								<div class="about-count-innr">
									<h4 class="text-white"><span class="counter">{{matrial_count}}</span> +</h4>
									<p> MATRIAL NO.</p>
								</div>
							</li>
							<li class="col-lg-3 col-md-3 col-sm-4 col-6">
								<div class="about-count-innr">
									<h4 class="text-white"><span class="counter">30</span> +</h4>
									<p>YEARS IN BUSINESS</p>
								</div>
							</li>
							<li class="col-lg-3 col-md-3 col-sm-4 col-6">
								<div class="about-count-innr">
									<h4 class="text-white"><span class="counter">{{review_count}}</span> +</h4>
									<p>HAPPY CLIENTS</p>
								</div>
							</li>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-lg-5 d-xl-block d-none">
				<div class="about-rgt-img">
					<img src="{% static 'assets/images/about2.png' %}" alt="" class="img-fluid">
					<img src="{% static 'assets/images/banner.png' %}" alt="" class="border-img img-fluid">
				</div>
			</div>
		</div>
	</div>
</section>
<section class="product-sec tp-space">
	<div class="container">
		<div class="heading justify-content-center mb-3">
			<div class="heading-icon">
				<img src="{% static 'assets/images/heading-icon.png' %}" alt="">
			</div>
			<div class="heading-content">
				<h3> Top Rated <br>Labour.</h3>
			</div>
		</div>
		<div class="row">
			{% for x in labour_list %}
			<div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
				<div class="product-innr">
					<div class="product-img">
						<img src="{{x.image.url}}" alt="">
						<span class="product-rating"><i class="fas fa-star"></i> 4.9</span>
					</div>
					<div class="product-content">
						<h4><a href="/labour-update/{{x.pk}}/">{{x.expert_title}}</a></h4>
						<p><i class="fas fa-map-marker-alt me-1"></i> {{x.address}}</p>
						<h6 class="text-white">{{x.name}}</h6>
						
						<div class="product-prc">
							<div>
								<p>{{x.mobile}}</p>
							</div>
							<div>
								<a href="javascript:void(0);" class="labour-fav" data-id="{{ x.id }}"><i class="far fa-bookmark"></i></a>
								<a href="javascript:void(0);" class="labour-com" data-id="{{ x.id }}"><i class="fas fa-sliders-h"></i></a>
							</div>
						</div>
					</div>
					<div class="product-social">
						<a href="javascript:void(0);"><i class="far fa-phone fa-rotate-90"></i></a>
						<a href="javascript:void(0);"><i class="fab fa-whatsapp"></i></a>
						<a href="javascript:void(0);"><i class="far fa-envelope"></i></a>
					</div>
				</div>
			</div>
			{% endfor %}
			<div class="col-lg-12 text-center">
				<a href="/labour-list/" class="thm-btn mt-5">View All</a>
			</div>
		</div>
	</div>
</section>
<section class="product-sec tp-space">
	<div class="container">
		<div class="heading justify-content-center mb-3">
			<div class="heading-icon">
				<img src="{% static 'assets/images/heading-icon.png' %}" alt="">
			</div>
			<div class="heading-content">
				<h3> luxurious <br>matrial.</h3>
			</div>
		</div>
		<div class="row">
			{% for x in matrial_list %}
			<div class="col-xl-3 col-lg-4 col-md-6 col-sm-6">
				<div class="product-innr">
					<div class="product-img">
						<img src="{{x.image.url}}" alt="">
						<span class="product-rating"><i class="fas fa-star"></i> 4.9</span>
					</div>
					<div class="product-content">
						<h4><a href="/matrial-update/{{x.pk}}/">{{x.name}}</a></h4>
						<!-- <p><i class="fas fa-map-marker-alt me-1"></i> {{x.name}}</p> -->
						<h6 class="text-white">{{x.type}}</h6>
						
						<div class="product-prc">
							<div>
								<p>INR {{x.start_rate}}-{{x.end_rate}}</p>
							</div>
							<div>
								<a href="javascript:void(0);" class="matrial-fav" data-id="{{ x.id }}"><i class="far fa-bookmark"></i></a>
								<a href="javascript:void(0);" class="matrial-com" data-id="{{ x.id }}"><i class="fas fa-sliders-h"></i></a>
							</div>
						</div>
					</div>
					<div class="product-social">
						<a href="javascript:void(0);"><i class="far fa-phone fa-rotate-90"></i></a>
						<a href="javascript:void(0);"><i class="fab fa-whatsapp"></i></a>
						<a href="javascript:void(0);"><i class="far fa-envelope"></i></a>
					</div>
				</div>
			</div>
			{% endfor %}
			<div class="col-lg-12 text-center">
				<a href="/matrial-list/" class="thm-btn mt-5">View All</a>
			</div>
		</div>
	</div>
</section>
		
		
		<section class="project-sec tp-space">
			<div class="container">
				<div class="heading new-head">
					<div class="heading-icon">
						<img src="{% static 'assets/images/heading-icon.png' %}" alt="">
					</div>
					<div class="heading-content">
						<h3> Explore our experts</h3>
						<p>Gain valuable real estate expertise with our latest insights from industry experts.</p>
					</div>
				</div>
				<div class="owl-carousel owl-theme" id="project-slider">
					<div class="row project-slider-innr g-0">
						<div class="col-lg-4 col-md-12">
							<img src="{% static 'assets/images/slider3.webp' %}" alt="" class="w-100">
						</div>
						<div class="col-lg-8 col-md-12">
							<div class="project-slider-contnt">
								<h4>Affordable Housing Solutions</h4>
								<p class="mb-3">Low Cost Construction Service Point</p>
								<p class="mb-3">Customized Home Building</p>
								<p class="mb-3">Sustainable Construction</p>
								<p class="mb-5">We specialize in cost-effective housing solutions, ensuring quality and durability at the best price.</p>
								<a href="javascript:void(0);" class="thm-btn">View All</a>
							</div>
						</div>
					</div>
					<div class="row project-slider-innr g-0">
						<div class="col-lg-4">
							<img src="{% static 'assets/images/slider2.webp' %}" alt="" class="w-100">
						</div>
						<div class="col-lg-8">
							<div class="project-slider-contnt">
								<h4>Reliable Labour Supply</h4>
								<p class="mb-3">Labour Provider</p>
								<p class="mb-3">Skilled & Unskilled Workforce</p>
								<p class="mb-3">On-Demand Manpower</p>
								<p class="mb-5">We connect construction projects with the right workforce to ensure smooth operations and efficiency.</p>
								<a href="javascript:void(0);" class="thm-btn">View All</a>
							</div>
						</div>
					</div>
					<div class="row project-slider-innr g-0">
						<div class="col-lg-4">
							<img src="{% static 'assets/images/slider1.webp' %}" alt="" class="w-100">
						</div>
						<div class="col-lg-8">
							<div class="project-slider-contnt">
								<h4>Quality Construction Materials</h4>
								<p class="mb-3">Material Provider</p>
								<p class="mb-3">Cement, Steel & Bricks</p>
								<p class="mb-3">Bulk & Retail Supply</p>
								<p class="mb-5">Get the best quality materials at competitive prices for all your construction needs.</p>
								<a href="javascript:void(0);" class="thm-btn">View All</a>
							</div>
						</div>
					</div>
					<div class="row project-slider-innr g-0">
						<div class="col-lg-4">
							<img src="{% static 'assets/images/slider4.webp' %}" alt="" class="w-100">
						</div>
						<div class="col-lg-8">
							<div class="project-slider-contnt">
								<h4>Real Estate Solutions</h4>
								<p class="mb-3">Properties Provider</p>
								<p class="mb-3">Residential & Commercial</p>
								<p class="mb-3">Affordable & Premium Listings</p>
								<p class="mb-5">Find the perfect property that suits your budget and requirements with our expert assistance.</p>
								<a href="javascript:void(0);" class="thm-btn">View All</a>
							</div>
						</div>
					</div>
				</div>
				
			</div>
		</section>
		
		
		
		<section class="ofc-location tp-space">
			<div class="container">
				<div class="heading new-head">
					<div class="heading-icon">
						<img src="{% static 'assets/images/heading-icon.png' %}" alt="">
					</div>
					<div class="heading-content">
						<h3>Visit Our office</h3>
					</div>
				</div>
				<div class=" owl-carousel owl-theme" id="location-slider">
					<div class="item location-innr">
						<img src="{% static 'assets/images/project1.webp' %}" alt="">
					</div>
					<div class="item location-innr">
						<img src="{% static 'assets/images/office-02.webp' %}" alt="">
					</div>
					<div class="item location-innr">
						<img src="{% static 'assets/images/project2.webp' %}" alt="">
					</div>
					<div class="item location-innr">
						<img src="{% static 'assets/images/about3.png' %}" alt="">
					</div>
					<div class="item location-innr">
						<img src="{% static 'assets/images/project3.webp' %}" alt="">
					</div>
					<div class="item location-innr">
						<img src="{% static 'assets/images/office-02.webp' %}" alt="">
					</div>
					<div class="item location-innr">
						<img src="{% static 'assets/images/project4.webp' %}" alt="">
					</div>
					<div class="item location-innr">
						<img src="{% static 'assets/images/project5.webp' %}" alt="">
					</div>
				</div>
			</div>
		</section>
		<section class="cta-sec tp-space">
			<div class="container">
				<div class="heading new-head">
					<div class="heading-icon">
						<img src="{% static 'assets/images/heading-icon.png' %}" alt="">
					</div>
					<div class="heading-content">
						<h3>Advisory Experts</h3>
						<p>Fill form below and our agent will contact you shortly</p>
					</div>
				</div>
				<div class="row">
					<div class="col-lg-12">
						<div class="cta-innr">
							<form action="" id="contact-add" class="row align-items-end">
								{% csrf_token %}
								<div class="col-lg-3 col-md-6 col-sm-6 mb-5">
									<input type="text" name="name" class="form-control" placeholder="Enter Name">
								</div>
								<div class="col-lg-3 col-md-6 col-sm-6 mb-5">
									<input type="number" name="mobile" class="form-control" placeholder="Enter Phone Number">
								</div>
								<div class="col-lg-3 col-md-6 col-sm-6 mb-5">
									<textarea name="desc" id="" class="form-control" placeholder="Enter Description"></textarea>
									
								</div>
								<div class="col-lg-3 col-md-6 col-sm-6 mb-5">
									<button class="thm-btn w-75" type="submit">Send</button>
								</div>
							</form>
							<div class="row justify-content-center">
								<div class="col-lg-4">
									<div class="product-social">
										<a href="javascript:void(0);"><i class="far fa-phone fa-rotate-90"></i></a>
										<a href="javascript:void(0);"><i class="fab fa-whatsapp"></i></a>
										<a href="javascript:void(0);"><i class="far fa-envelope"></i></a>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		{% endblock body %} 

templates/labour-details.html
{% extends 'base.html' %}
{% load static %}
<title>{% block title %}Labour Details{% endblock %}</title>
{% block body %}
		<section class="agent-detal space mn-h">
			<div class="container">
				<h3 class="fz-28 fw-600 primary-clr font-2 text-center mb-3">Member Details</h3>
				<div class="row">
					<div class="col-lg-12 ">
						<div class="agent-detal-inr p-20">
							<div class="row">
								<div class="col-xl-4 col-lg-3 col-md-3 col-sm-4 col-12">
									<div class="agent-detal-inr-img"><a href="/labour-review-add/{{labour_list.pk}}/">
										<img src="{{labour_list.image.url}}" alt=""></a>
									</div>
								</div>
								<div class="col-xl-8 col-lg-9 col-md-9 col-sm-8 col-12">
									<div class="agent-detal-inr-cntnt">
										<h4 class="fz-22 fw-400 text-white text-uppercase">{{labour_list.name}}</h4>
										<h5 class="fz-14 fw-400 text-secondary text-capitalize">{{labour_list.expert_title}}</h5>
										<p> <span>Experience:</span> <span>3+ years</span> </p>
										<p> <span>Mobile:</span> <span>{{ labour_list.mobile }}</span> </p>
										<p> <span>Languages:</span> <span>Hindi</span> </p>
										<div class="inquiry-btn">
											<div class="product-social">
												<a href="javascript:void(0);"><i class="far fa-phone fa-rotate-90"></i></a>
												<a href="javascript:void(0);"><i class="fab fa-whatsapp"></i></a>
												<a href="javascript:void(0);"><i class="far fa-envelope"></i></a>
											</div>
											<div>
												<a href="tel:{{labour_list.mobile}}" class="thm-btn">Call Now</a>
											</div>
										</div>
									</div>
								</div>
								<div class="col-lg-12">
									<div class="agent-detal-desc p-10">
										<p class="fz-14 mb-3">{{labour_list.desc}}.</p>
										<p class="fz-14 mb-3">{{labour_list.desc}}.
											{{labour_list.desc}}.</p>
									</div>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<section class="review-sec agent-review tp-space">
			<div class="container">
				<h3 class="fz-28 fw-600 font-2 text-center font-2 primary-clr mb-5">Review</h3>
				<div class="row align-items-center">
					<div class="col-lg-12">
						<div class="review-rgt ">
							<div class="owl-carousel owl-theme" id="testimonial-slider">
								{% for x in labour_review %}
								<div class="item review-slider-item">
									<div class="review-slider-innr">
										<p>“{{x.desc}}”</p>
										<div class="review-slider-innr-star">
											<h5>{{x.mobile}}</h5>
											<h5>{{x.user_name}}</h5>
										</div>
									</div>
									<!-- <img src="{% static 'assets/images/testimonial-img-01.png' %}" alt=""> -->
								</div>
								{% endfor %}
							</div>
						</div>
					</div>
				</div>
			</div>
		</section>
		<section class="agent-list agent-dtl-list tp-space">
			<div class="container">
				<h4 class="fz-28 fw-600 text-white text-center font-2 mb-4">Our Member</h4>
				<div class="row justify-content-center">
					{% for x in labours %}
					<div class="col-xl-3 col-lg-4 col-md-4 col-sm-6">
						<div class="product-innr">
							<div class="product-img">
								<img src="{{x.image.url}}" alt="">
								<span class="product-rating"><i class="fas fa-star"></i> 4.9</span>
							</div>
							<div class="product-content">
								<h4><a href="/labour-update/{{x.pk}}/">{{x.expert_title}}</a></h4>
								<p><i class="fas fa-map-marker-alt me-1"></i> {{x.address}}</p>
								<h6 class="text-white">{{x.name}}</h6>
								
								<div class="product-prc">
									<div>
										<p>{{x.mobile}}</p>
									</div>
									<div>
										<a href="javascript:void(0);" class="labour-fav" data-id="{{ x.id }}"><i class="far fa-bookmark"></i></a>
										<a href="javascript:void(0);" class="labour-com" data-id="{{ x.id }}"><i class="fas fa-sliders-h"></i></a>
									</div>
								</div>
							</div>
							<div class="product-social">
								<a href="javascript:void(0);"><i class="far fa-phone fa-rotate-90"></i></a>
								<a href="javascript:void(0);"><i class="fab fa-whatsapp"></i></a>
								<a href="javascript:void(0);"><i class="far fa-envelope"></i></a>
							</div>
						</div>
					</div>
					{% endfor %}
					
				</div>
			</div>
		</section>
		{% endblock body %}